import { useState, createElement as h } from "react";

const FEATURES = [
  { icon: "\ud83d\udcca", title: "50+ Ratios Financiers", desc: "P/E, EV/EBITDA, ROE, ROA, marges, dette nette, ROIC et bien plus." },
  { icon: "\ud83d\udcc8", title: "Graphiques Interactifs", desc: "Chandeliers japonais, moyennes mobiles, Bollinger." },
  { icon: "\ud83c\udfe6", title: "\u00c9tats Financiers Complets", desc: "Bilan, r\u00e9sultats et tr\u00e9sorerie sur 10 ans. Export CSV." },
  { icon: "\u2696\ufe0f", title: "Comparaison", desc: "Comparez 2 entreprises c\u00f4te \u00e0 c\u00f4te." },
  { icon: "\ud83c\udfc6", title: "Top Investisseurs", desc: "Portefeuilles de Buffett, Wood, Burry." },
  { icon: "\u2b50", title: "Watchlist & Alertes", desc: "Favoris et alertes moyennes mobiles." },
  { icon: "\ud83c\udfaf", title: "Score Sant\u00e9", desc: "Score 0-100 sur 6 crit\u00e8res cl\u00e9s." },
  { icon: "\ud83c\udf0d", title: "Couverture Mondiale", desc: "NYSE, NASDAQ, Euronext, Tokyo et plus." },
];

const TESTIMONIALS = [
  { name: "Thomas D.", role: "Investisseur", text: "Alphaview remplace 3 outils payants.", stars: 5 },
  { name: "Marie L.", role: "\u00c9tudiante", text: "Parfait pour mes \u00e9tudes !", stars: 5 },
  { name: "Pierre K.", role: "Analyste", text: "Un outil s\u00e9rieux, impressionnant.", stars: 5 },
];

const POPULAR = [
  { symbol: "AAPL", name: "Apple" }, { symbol: "MSFT", name: "Microsoft" },
  { symbol: "GOOGL", name: "Alphabet" }, { symbol: "NVDA", name: "NVIDIA" },
  { symbol: "TSLA", name: "Tesla" }, { symbol: "AMZN", name: "Amazon" },
  { symbol: "MC.PA", name: "LVMH" }, { symbol: "OR.PA", name: "L'Or\u00e9al" },
  { symbol: "AI.PA", name: "Air Liquide" }, { symbol: "SAN.PA", name: "Sanofi" },
];

export default function LandingPage({ onSearch, onShowAuth }) {
  const [email, setEmail] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  const handleNL = (e) => { e.preventDefault(); if (!email.trim()) return; try { const l = JSON.parse(localStorage.getItem("av_newsletter") || "[]"); if (!l.includes(email.trim())) { l.push(email.trim()); localStorage.setItem("av_newsletter", JSON.stringify(l)); } } catch {} setSubscribed(true); setEmail(""); };
  const S = (tag, props, ...kids) => h(tag, props, ...kids);
  return S("div", { className: "landing" },
    S("section", { className: "landing-hero" }, S("div", { className: "landing-hero-bg" }), S("div", { className: "landing-hero-content" }, S("div", { className: "landing-badge" }, "\ud83d\ude80 100% Gratuit \u00b7 Aucune carte requise"), S("h1", { className: "landing-h1" }, "L'outil ", S("span", { className: "landing-gradient" }, "n\u00b01"), " d'analyse", S("br"), "fondamentale boursi\u00e8re"), S("p", { className: "landing-subtitle" }, "Analysez n'importe quelle action mondiale. Cours temps r\u00e9el, 50+ ratios, \u00e9tats financiers sur 10 ans."), S("div", { className: "landing-cta-group" }, S("button", { className: "landing-cta-primary", onClick: () => onSearch("AAPL") }, "Essayer gratuitement \u2192"), S("button", { className: "landing-cta-secondary", onClick: onShowAuth }, "Cr\u00e9er un compte")), S("div", { className: "landing-stats" }, S("div", { className: "landing-stat" }, S("span", { className: "landing-stat-value" }, "50+"), S("span", { className: "landing-stat-label" }, "Ratios")), S("div", { className: "landing-stat-divider" }), S("div", { className: "landing-stat" }, S("span", { className: "landing-stat-value" }, "70K+"), S("span", { className: "landing-stat-label" }, "Actions")), S("div", { className: "landing-stat-divider" }), S("div", { className: "landing-stat" }, S("span", { className: "landing-stat-value" }, "10 ans"), S("span", { className: "landing-stat-label" }, "Historique")), S("div", { className: "landing-stat-divider" }), S("div", { className: "landing-stat" }, S("span", { className: "landing-stat-value" }, "100%"), S("span", { className: "landing-stat-label" }, "Gratuit"))))),
    S("section", { className: "landing-section" }, S("h2", { className: "landing-section-title" }, "Actions populaires"), S("p", { className: "landing-section-desc" }, "Cliquez sur une action pour commencer"), S("div", { className: "landing-stocks-grid" }, POPULAR.map(s => S("button", { key: s.symbol, className: "landing-stock-chip", onClick: () => onSearch(s.symbol) }, S("span", { className: "landing-stock-symbol" }, s.symbol), S("span", { className: "landing-stock-name" }, s.name))))),
    S("section", { className: "landing-section" }, S("h2", { className: "landing-section-title" }, "Tout ce dont vous avez besoin"), S("p", { className: "landing-section-desc" }, "Des fonctionnalit\u00e9s pro, accessibles \u00e0 tous"), S("div", { className: "landing-features-grid" }, FEATURES.map(f => S("div", { key: f.title, className: "landing-feature-card" }, S("div", { className: "landing-feature-icon" }, f.icon), S("h3", { className: "landing-feature-title" }, f.title), S("p", { className: "landing-feature-desc" }, f.desc))))),
    S("section", { className: "landing-section landing-pricing-section" }, S("h2", { className: "landing-section-title" }, "Un prix simple"), S("p", { className: "landing-section-desc" }, "Gratuit ou Pro"), S("div", { className: "landing-pricing-grid" }, S("div", { className: "landing-price-card" }, S("div", { className: "landing-price-badge" }, "Gratuit"), S("div", { className: "landing-price-amount" }, "0\u20ac", S("span", null, "/mois")), S("p", { className: "landing-price-desc" }, "Pour d\u00e9couvrir"), S("ul", { className: "landing-price-features" }, S("li", null, "\u2713 10 analyses/jour"), S("li", null, "\u2713 30+ ratios"), S("li", null, "\u2713 Bilan, r\u00e9sultats"), S("li", null, "\u2713 Graphiques"), S("li", null, "\u2713 Watchlist 5 max"), S("li", { className: "landing-price-disabled" }, "\u2717 Comparaison"), S("li", { className: "landing-price-disabled" }, "\u2717 Export CSV"), S("li", { className: "landing-price-disabled" }, "\u2717 Score sant\u00e9")), S("button", { className: "landing-price-btn", onClick: () => onSearch("AAPL") }, "Commencer")), S("div", { className: "landing-price-card landing-price-pro" }, S("div", { className: "landing-price-popular" }, "\u2b50 Plus populaire"), S("div", { className: "landing-price-badge" }, "Pro"), S("div", { className: "landing-price-amount" }, "9.99\u20ac", S("span", null, "/mois")), S("p", { className: "landing-price-desc" }, "Pour investisseurs s\u00e9rieux"), S("ul", { className: "landing-price-features" }, S("li", null, "\u2713 Illimit\u00e9"), S("li", null, "\u2713 50+ ratios"), S("li", null, "\u2713 Comparaison"), S("li", null, "\u2713 Export CSV"), S("li", null, "\u2713 Score sant\u00e9"), S("li", null, "\u2713 Top investisseurs"), S("li", null, "\u2713 Alertes MA")), S("button", { className: "landing-price-btn landing-price-btn-pro", onClick: onShowAuth }, "Essai 14 jours \u2192")))),
    S("section", { className: "landing-section" }, S("h2", { className: "landing-section-title" }, "Ils nous font confiance"), S("div", { className: "landing-testimonials-grid" }, TESTIMONIALS.map(t => S("div", { key: t.name, className: "landing-testimonial-card" }, S("div", { className: "landing-testimonial-stars" }, "\u2605".repeat(t.stars)), S("p", { className: "landing-testimonial-text" }, t.text), S("div", { className: "landing-testimonial-author" }, S("strong", null, t.name), S("span", null, t.role)))))),
    S("section", { className: "landing-section landing-newsletter-section" }, S("div", { className: "landing-newsletter-card" }, S("h2", { className: "landing-newsletter-title" }, "Restez inform\u00e9"), S("p", { className: "landing-newsletter-desc" }, "Analyses hebdomadaires et nouveaut\u00e9s Alphaview."), subscribed ? S("div", { className: "landing-newsletter-success" }, "\u2705 Inscrit !") : S("form", { className: "landing-newsletter-form", onSubmit: handleNL }, S("input", { type: "email", placeholder: "votre@email.com", value: email, onChange: e => setEmail(e.target.value), className: "landing-newsletter-input", required: true }), S("button", { type: "submit", className: "landing-newsletter-btn" }, "S'inscrire \u2192")), S("p", { className: "landing-newsletter-privacy" }, "Pas de spam."))),
    S("section", { className: "landing-section landing-final-cta" }, S("h2", { className: "landing-final-title" }, "Pr\u00eat \u00e0 analyser comme un pro ?"), S("p", { className: "landing-final-desc" }, "Rejoignez des milliers d'investisseurs."), S("button", { className: "landing-cta-primary landing-cta-large", onClick: () => onSearch("AAPL") }, "Commencer \u2014 C'est gratuit \u2192"))
  );
                  }
